spring:
  datasource:
    url: jdbc:h2:mem:helloworld
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    deferDatasourceInitialization: true
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: update
  h2:
    console:
      enabled: true
      path: /h2-ui    